# Generated by Django 4.1 on 2022-10-02 06:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('new_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
