# Generated by Django 4.1 on 2022-10-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_news_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news_test',
        ),
    ]
