# Generated by Django 4.1 on 2022-10-02 08:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0003_delete_news_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('news_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
