# Generated by Django 4.1 on 2022-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0005_news_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='upl_img',
            field=models.FileField(default=None, null=True, upload_to='jpeg/'),
        ),
    ]
