# Generated by Django 4.1 on 2022-10-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0006_news_upl_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=75)),
                ('profile_pic', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
