# Generated by Django 4.1 on 2023-02-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0009_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='experience',
            field=models.BooleanField(default='none', null=True),
        ),
    ]
