# Generated by Django 4.1.7 on 2023-05-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0011_dropdown_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='select_muliple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
