# Generated by Django 4.1.7 on 2023-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0013_advancedajax'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedajax',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
