# Generated by Django 4.1.7 on 2023-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0015_advancedajax_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedajax',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='ProfileImage'),
        ),
    ]
